#!/bin/bash
<<Documentation
Name:***********
Date:
Description:Write a script to print chess board
Sample_i/p: NIL
sample_o/p:8x8 black and white colored chessboard
Documentation
 
for i in `seq 8`                                         #Loop will run depending upon the i value     
do
        for j in `seq 8`                                 #Loop will run depending upon the j value
        do
            if [ $((( $i + $j) % 2 )) -eq 0 ]            #Checking the condition i+j modulus 2 equal to zero or not
            then 
                echo -e -n "\e[47m" " "                  #printing white colored box
            else
                echo -e -n "\e[40m" " "                  #printing black colored box
            fi
 
        done
        echo -e "\e[0m" " "                              # to normalise
 done
