#!/bin/bash
<<Documentation
Name:***** ******
Date:
Description:Script for arithmetic calculator using command line arguments
Sample_i/p:
1. ./arithmatic_calc.sh 25 + 41
2. ./arithmatic_calc.sh 10 x 5
3. ./arithmatic_calc.sh 25 / 5
4. ./arithmatic_calc.sh 10.2 – 5.6
5. ./arithmatic_calc.sh
6. ./arithmatic_calc.sh 3.4
sample_o/p:
1.25 + 41 = 66
2.10 x 5 = 50
3.25 / 5 = 5.00
4.10.2 – 5.6 = 4.6
5.Error : Please pass the arguments through command line.
  Usage:./arithmatic_calc.sh 2.3 + 6.7
6.Error:Please pass 3 arguments.
  Usage:./arithmatic_calc.sh 2.3 + 6.7
Documentation

if [ $# -eq 0 ]                                                            #checking total number of argument is equal to zero
then    
        echo "Error : Please pass the arguments through command line.
              Usage:./arithmatic_calc.sh 2.3 + 6.7"
elif [ $# -lt 3 ]                                                          #checking total number of argument is less than three
then 
        echo "Error:Please pass 3 arguments.
              Usage:./arithmatic_calc.sh 2.3 + 6.7"
elif [ $# -eq 3 ]                                                          #checking total number equal to three
then
        case $2 in                                                         #checking which operator to use
                +)s=`echo "$1+$3"|bc`                                      #addition operation
                        echo "$1 + $3 = $s"                                                                
                ;;
                x)s=`echo "$1*$3" | bc`                                    #multiplication operation
                        echo "$1 x $3 = $s"
                ;;
                /)s=`echo "scale=2;$1/$3" | bc`                            #division operation
                        echo "$1 / $3 = $s"
                ;;
                -)s=`echo "scale=2;$1-$3" | bc`                            #substraction operation
                        echo "$1 - $3 = $s"
                ;;
                *)echo "Error:Invalid Argument!!!"                         #Error if entered wrong operator
                ;;
        esac
fi
